import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { Poppins } from 'next/font/google'
import Navigation from '@/components/navigation'

const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
  display: 'swap'
})

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className={poppins.className}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className='flex justify-center'>
          <Navigation />
        </div>

        {children}
      </body>
    </html>
  )
}
